In [1]:
def wallis(n):
    pi = 2 
    for i in range(1,n):
        left = (2 * i)/(2 * i -1)
        right = (2 * i)/(2 * i + 1)
        pi = pi * left * right 
    return pi
print(wallis(300))

3.1389713844929354


In [1]:
def nth_fibonacci(n):
    if n <= 1:
        return n
    return nth_fibonacci(n-1) + nth_fibonacci(n-2)

n = int(input("Enter a number: "))
result = nth_fibonacci(n)
print(result)


55


In [ ]:
Li = [3]
C = [6]
Na = [11]

if Li >= C:
    print("Li is greater than or equal to C")
else:
    print("Li is less than C")

if Na <= C:
    print("Na is less than or equal to C")
else:
    print("Na is greater than C")

    if Li >= C:
        print("Both Na and Li are greater than or equal to C")
    else:
        print("Na is greater than C but Li is less than C")

if Na < C and Li < C:
    print("Both Na and Li are less than C")
elif C >= Li and Na < C:
    print("C and Na are greater than Li")

if Li < C and Li< Na:
    print("C and Na are greater than Li")


Li is less than C
Na is greater than C
Na is greater than C but Li is less than C
C and Na are greater than Li


In [2]:


adenine = "A"
Thymine = "T"
Gaunine = "G"
Cyostine = "C"
 
complimentary_strand = []
valid_pairs = [
		(adenine, Thymine),
		(Thymine, adenine),
		(Gaunine, Cyostine),
		(Cyostine, Gaunine)
	]
Dna_sequence = input("please Input DNA sequence")

for base in Dna_sequence:
	for pair in valid_pairs:
		if base == pair[0]:
			complimentary_strand.append(pair[1])
			break

print(complimentary_strand)



[]


In [ ]:
def rate(A0, k=1.0, n=1, units='M/s'):
    result = k * A0 ** n
    return f"{result} {units}"

print(rate(7.0, k=1.0, n=1))

7.0 M/s


In [2]:
import numpy as np

file_path = r'C:\Users\noahd\Downloads\water (1).xyz'

data = np.genfromtxt(file_path, skip_header=2, dtype='unicode')
print(data)

atoms = data[:, 0]
coodrdinates = data[:, 1:].astype(float)

print("Atoms name:")
print(atoms)

print("\nAtom coordinates:")
print(coodrdinates)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]
Atoms name:
['O' 'H1' 'H2']

Atom coordinates:
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [6]:
Ar1 = np.arange(15)
print("Ar1:")
print(Ar1)

Ar1_reshaped = Ar1.reshape(3,5)
print("n\Reshaped array (3 by 5):")
print(Ar1_reshaped)

Ar1_transposed = Ar1_reshaped.T
print("\nTransposed array (5 by 3):")
print(Ar1_transposed)

Ar1_flat = Ar1_transposed.ravel()
print("\nFlat array:")
print(Ar1_flat)

Ar1:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
n\Reshaped array (3 by 5):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Transposed array (5 by 3):
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

Flat array:
[ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]


In [11]:
Ar2 = np.random.randint(0, high=10, size=15).reshape(5, 3)
print("\nRandom 2D array (5x3):")
print(Ar2)

element = Ar2[1, 2]
print("\nSecond element of the third column:")
print(element)

third_row = Ar2[2, :]
print("\nThird row:")
print(third_row)

first_column = Ar2[:, 0]
print("\nFirst column:")
print(first_column)

last_two_elements = Ar2[0, -2:]
print("\nLast two elements of the first row:")
print(last_two_elements)


Random 2D array (5x3):
[[5 0 0]
 [5 2 7]
 [7 7 6]
 [1 9 4]
 [1 1 5]]

Second element of the third column:
7

Third row:
[7 7 6]

First column:
[5 5 7 1 1]

Last two elements of the first row:
[0 0]
